spring:
  jpa:
    # 展示执行的sql
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    url: jdbc:none:3306/none?useSSL=false&serverTimezone=UTC
    username: none
    password: none
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10086

